on:
  - pull_request
  - push

name: backwards compatibility

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@13cb4941a5965cb2bbf16ed0578d2f8b04e978cb # master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
