on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
      - 'psalm.xml'

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
      - 'psalm.xml'

name: Composer require checker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  composer-require-checker:
    uses: yiisoft/actions/.github/workflows/composer-require-checker.yml@13cb4941a5965cb2bbf16ed0578d2f8b04e978cb # master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4', '8.5']
