on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: mariadb

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tests:
    name: PHP ${{ matrix.php }}-mariadb-${{ matrix.mariadb.version }}

    env:
      extensions: pdo, pdo_mysql

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
        mariadb:
          - version: 12
            image: mariadb:12@sha256:628f228f0fd5913a220438693576b29b6fe4dc1fa0a1298c0e98579fae28635f
        include:
          - php: 8.5
            mariadb:
              version: 10.4
              image: mariadb:10.4@sha256:22edfe1c78349f8cae88bbb5c2873b7e6c515be767c91c691308ce57445806f3
          - php: 8.5
            mariadb:
              version: 10.5
              image: mariadb:10.5@sha256:a530aeeefd82f4fa5150f391b6c75462140904780338766f6b03acecb1cca3ce
          - php: 8.5
            mariadb:
              version: 10.6
              image: mariadb:10.6@sha256:114d40be36852d0a019afd8458f7e1cc63fd300403b115b1f32e31130d5f671b
          - php: 8.5
            mariadb:
              version: 10.7
              image: mariadb:10.7@sha256:9a48ac9f196f3d4fd6fea2cab59a49df9e7ca459bf14b2f7b85a0e38a5454571
          - php: 8.5
            mariadb:
              version: 10.8
              image: mariadb:10.8@sha256:456709ab146585d6189da05669b84384518baecd83670c9e5221f8c20a47cf1e
          - php: 8.5
            mariadb:
              version: 10.9
              image: mariadb:10.9@sha256:56710811b0b96233ef84f4982d3337d88d3aa46a68f3fcb2853b94e1d04ea25c

    services:
      mysql:
        image: ${{ matrix.mariadb.image }}
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_DATABASE: translator-message-db-test
          MARIADB_USER: yii
          MARIADB_PASSWORD: 'q1w2e3r4'
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Update composer.
        run: composer self-update

      - name: Remove unused dependencies of DB drivers
        run: composer remove --dev yiisoft/db-sqlite yiisoft/db-pgsql yiisoft/db-mssql yiisoft/db-oracle

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Mysql --coverage-clover=coverage.xml --colors=always
        env:
          ENVIRONMENT: ci
          YII_MYSQL_DATABASE: translator-message-db-test
          YII_MYSQL_HOST: 127.0.0.1
          YII_MYSQL_PORT: 3306
          YII_MYSQL_USER: yii
          YII_MYSQL_PASSWORD: q1w2e3r4

      - name: Upload coverage to Codecov.
        if: matrix.php == '8.1'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
