name: Rector + PHP CS Fixer

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rector-cs.yml'
      - 'composer.json'
      - 'rector.php'
      - '.php-cs-fixer.dist.php'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector-cs.yml@13cb4941a5965cb2bbf16ed0578d2f8b04e978cb # master
    with:
      php: '8.1'
